package swag

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"sync/atomic"

	"github.com/swaggest/swgui/v5emb"
	swaggo "github.com/swaggo/swag"

	"github.com/xbcio/xbc/plugin"
	"github.com/xbcio/xbc/transport/web"
)

// Key is Swag's stable Definition and configuration identity.
const Key plugin.Key = "swag"

type documentMetadata struct {
	Swagger string `json:"swagger"`
	OpenAPI string `json:"openapi"`
	Info    struct {
		Title string `json:"title"`
	} `json:"info"`
}

type handlerSnapshot struct {
	handler http.Handler
}

// Plugin serves one immutable document generated by swaggo/swag and its
// embedded Swagger UI.
type Plugin struct {
	settings settings
	document []byte
	title    string
	ui       atomic.Pointer[handlerSnapshot]
}

var (
	_ web.RouteContributor     = (*Plugin)(nil)
	_ web.RouteCatalogListener = (*Plugin)(nil)
)

var definition = plugin.DefineConfigured(
	Key,
	plugin.ConfigSpec[Config]{
		Defaults: DefaultConfig,
		Prepare:  prepareConfig,
	},
	func(_ plugin.BuildContext, cfg Config) (*Plugin, error) {
		return newPlugin(cfg, func(name string) (string, error) { return swaggo.ReadDoc(name) })
	},
	plugin.Options[*Plugin]{
		Activation: plugin.WhenConfigured("plugins." + Key.String()),
		Exports: plugin.Contracts(
			plugin.ExportAs[web.RouteContributor](func(value *Plugin) web.RouteContributor { return value }),
			plugin.ExportAs[web.RouteCatalogListener](func(value *Plugin) web.RouteCatalogListener { return value }),
		),
	},
)

var bundle = plugin.BundleOf(definition)

// New constructs a directly usable Plugin from a generated swag document.
// Application composition normally uses Bundle and imports its generated docs
// package so swaggo/swag registers the configured instance before construction.
func New(document swaggo.Swagger) (*Plugin, error) {
	if document == nil {
		return nil, fmt.Errorf("swag: generated document is nil")
	}
	return newPlugin(DefaultConfig(), func(string) (string, error) {
		return document.ReadDoc(), nil
	})
}

func newPlugin(cfg Config, readDocument func(string) (string, error)) (*Plugin, error) {
	normalized, err := normalizeConfig(cfg)
	if err != nil {
		return nil, err
	}
	if readDocument == nil {
		return nil, fmt.Errorf("swag: document reader is nil")
	}

	raw, err := readDocument(normalized.instanceName)
	if err != nil {
		return nil, fmt.Errorf("swag: read generated document %q: %w", normalized.instanceName, err)
	}
	document := []byte(raw)
	var metadata documentMetadata
	if err := json.Unmarshal(document, &metadata); err != nil {
		return nil, fmt.Errorf("swag: generated document %q is not valid JSON: %w", normalized.instanceName, err)
	}
	if metadata.Swagger == "" && metadata.OpenAPI == "" {
		return nil, fmt.Errorf("swag: generated document %q declares neither swagger nor openapi version", normalized.instanceName)
	}
	title := metadata.Info.Title
	if title == "" {
		title = "Swagger UI"
	}

	return &Plugin{
		settings: normalized,
		document: append([]byte(nil), document...),
		title:    title,
	}, nil
}

// Definition returns Swag's canonical immutable declaration handle.
func Definition() plugin.Definition { return definition }

// Bundle returns Swag's side-effect-free explicit composition bundle.
func Bundle() plugin.Bundle { return bundle }

// RegisterRoutes contributes the generated JSON and optional embedded UI.
func (p *Plugin) RegisterRoutes(r *web.Router) {
	cfg := p.settings
	r.GET(cfg.jsonPath, p.serveDocument).
		Name("swag.document").
		Auth(web.Public())
	if !cfg.uiEnabled {
		return
	}

	ui := p.serveUI
	r.GET(cfg.uiPath, ui).
		Name("swag.ui").
		Auth(web.Public())
	r.GET(cfg.uiPath+"/*asset", ui).
		Name("swag.assets").
		Auth(web.Public())
}

// RoutesReady resolves the transport's final base-prefixed documentation paths
// and prepares Swagger UI before the global traffic gate opens.
func (p *Plugin) RoutesReady(routes web.RouteCatalog) error {
	if routes == nil {
		return fmt.Errorf("swag: route catalog is nil")
	}
	if !p.settings.uiEnabled {
		return nil
	}
	jsonPath, uiPath := documentationPaths(routes.All(), p.settings.jsonPath, p.settings.uiPath)
	p.ui.Store(&handlerSnapshot{handler: v5emb.New(p.title, jsonPath, uiPath+"/")})
	return nil
}

// Document returns a defensive copy of the generated JSON document.
func (p *Plugin) Document() []byte {
	if p == nil {
		return nil
	}
	return append([]byte(nil), p.document...)
}

func documentationPaths(routes []web.RouteInfo, fallbackJSON, fallbackUI string) (jsonPath, uiPath string) {
	for _, route := range routes {
		switch route.Name {
		case "swag.document":
			jsonPath = route.Path
		case "swag.ui":
			uiPath = route.Path
		}
	}
	if jsonPath == "" {
		jsonPath = fallbackJSON
	}
	if uiPath == "" {
		uiPath = fallbackUI
	}
	return jsonPath, uiPath
}

func (p *Plugin) serveUI(_ context.Context, c *web.Ctx) error {
	snapshot := p.ui.Load()
	if snapshot == nil || snapshot.handler == nil {
		web.AbortProblem(c, web.NewProblem(http.StatusServiceUnavailable, "documentation_not_ready"))
		return nil
	}
	snapshot.handler.ServeHTTP(c.Writer(), c.Request())
	return nil
}

func (p *Plugin) serveDocument(_ context.Context, c *web.Ctx) error {
	c.Data(http.StatusOK, "application/json; charset=utf-8", p.document)
	return nil
}
