// Package biz provides an optional HTTP business-response contract for
// XBC Web. It adopts GFA's useful explicit success-envelope and business-error
// ideas while preserving semantic HTTP statuses and RFC 9457 failures.
//
// # Usage
//
// Enable the biz.onerror middleware by composing its Bundle explicitly:
//
//	import (
//		"github.com/xbcio/xbc"
//		webprelude "github.com/xbcio/xbc/transport/web/prelude"
//		biz "github.com/xbcio/xbc/transport/web/extensions/response/biz"
//	)
//
//	func newApp() (*xbc.App, error) {
//		return xbc.New(xbc.WithBundles(
//			webprelude.Bundle(),
//			biz.Bundle(),
//		))
//	}
//
// Handlers opt into the success envelope explicitly; the plugin never wraps
// arbitrary JSON, streams, files, or third-party handlers behind their back.
// The wire model is {success, code, message, data, requestId}; paginated data is
// {list, total}. RequestId is copied only from a value already validated or
// generated by the request-ID plugin:
//
//	r.POST("/orders", func(ctx context.Context, c *web.Ctx) error {
//		order, err := service.Create(ctx)
//		if err != nil {
//			return err
//		}
//		return biz.Created(c, order)
//	})
//
// Paginated builds the page payload rather than writing it, so the page shape
// and the HTTP status stay independent:
//
//	return biz.OK(c, biz.Paginated(orders, total))
//
// A client-safe business rule failure can be returned from the HTTP application
// boundary and will become application/problem+json:
//
//	return biz.NewError(
//		"ORDER.ALREADY_PAID",
//		"The order has already been paid.",
//	).WithStatus(http.StatusConflict)
//
// NewError defaults to HTTP 422; WithStatus, WithCause and WithDetail vary the
// three optional dimensions. Each returns a copy, so a package-level Error works
// as a reusable template:
//
//	var ErrOrderClosed = biz.NewError("ORDER.CLOSED", "The order is closed.")
//	var ErrQuotaExhausted = biz.NewError("QUOTA.EXHAUSTED", "Quota of %d is exhausted.")
//
//	// Neither template is mutated by the call site.
//	return ErrOrderClosed.WithCause(dbErr)
//	return ErrQuotaExhausted.WithDetail(limit)
//
// WithDetail's arguments are published verbatim, so pass only client-safe
// values; an internal cause belongs in WithCause, which never reaches the
// response. A non-5xx failure that carries a cause is logged, because Web's
// outer boundary logs only 5xx and the cause would otherwise be lost.
//
// Invalid statuses or codes fail closed as a fixed 500. Error causes and unknown
// errors are never copied to the response.
// The middleware is built with web.OnError and composes with Web's outer safe
// boundary; panic recovery remains a separate responsibility. Domain packages
// should not import this package: keep protocol-neutral errors there and map
// them with web.ErrorMapper in an application plugin.
package biz
